#NB has been disabled for now, change branches: [ main] to enable
#workflow creates a dist branch for the core library, based on its package version
#should create the following 2 dist branches
#for example the core library with package version x.x.x will create branches: 
#dist_core
#dist_core_vx.x.x

name: CreateDist

on:
  push:
    branches: [ main-disabled ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: setup Node
      uses: actions/setup-node@v3
    - run: npm ci
    - run: npm run build:libs

    - name: version core
      uses: nyaa8/package-version@v1
      with:
       path: './dist/@ng-formworks/core/package.json'  
    
    - name: dist core versioned
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist_core_v${{ env.PACKAGE_VERSION }}
        FOLDER: ./dist/@ng-formworks/core
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: dist core
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: dist_core
        FOLDER: ./dist/@ng-formworks/core
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
